server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  application:
    name: customerservice

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: user
    password: password